#Logistic Regression

In this module, we will see the classification of the MNIST dataset using a logistic regression classifier. 

First we will import the packages needed for classification in sklearn.linear_model. The final accuracy is measured using the sklearn.metrics. Luckily, Keras already provides the MNIST dataset in keras.datasets.mnist.

In [0]:
from keras.datasets import mnist
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Using TensorFlow backend.


Now, we will load the datasets into four variables.

In [0]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

We will reshape the data so that it can be classified by the model.

In [0]:
image_vector = 28*28
x_train = x_train.reshape(x_train.shape[0], image_vector)
x_test = x_test.reshape(x_test.shape[0], image_vector)

We will now load the Logistic Regression model.

In [0]:
model = LogisticRegression(random_state=0, solver='lbfgs', max_iter=50,
                          multi_class="multinomial")

Now we train.

In [0]:
model.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=50, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

Now to validate the model created in the last cell.

In [0]:
y_pred = model.predict(x_test)

Now, to display the result.

In [0]:
print("Accuracy:\n", accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", confusion_matrix(y_test, y_pred))
print("Classification Report =\n", classification_report(y_test, y_pred))

Accuracy:
 0.9218
Confusion Matrix =
 [[ 963    0    0    3    0    4    5    3    2    0]
 [   0 1111    3    2    0    1    4    2   12    0]
 [   3    9  923   17    6    4   14   11   41    4]
 [   2    0   23  908    0   33    3   12   21    8]
 [   1    2    7    2  909    0   11    4    9   37]
 [  11    2    2   35   11  765   15    6   40    5]
 [  12    3    5    1    9   13  910    3    2    0]
 [   1    5   24    7    8    1    0  950    5   27]
 [   6   10    4   23    8   30    9   13  866    5]
 [  10    8    1   11   27    3    0   26   10  913]]
Classification Report =
               precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.97      1135
           2       0.93      0.89      0.91      1032
           3       0.90      0.90      0.90      1010
           4       0.93      0.93      0.93       982
           5       0.90      0.86      0.88       892
           6       0.94    