#Decision Trees

In this module, we will see the classification of the MNIST dataset using a Decision Tree. 

First we will import the packages needed for classification in sklearn.tree. The final accuracy is measured using the sklearn.metrics. Luckily, Keras already provides the MNIST dataset in keras.datasets.mnist.

In [1]:
from keras.datasets import mnist
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Using TensorFlow backend.


Now, we will load the datasets into four variables.

In [0]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

We will reshape the data so that it can be classified by the model.

In [0]:
image_vector = 28 * 28
x_train = x_train.reshape(x_train.shape[0], image_vector)
x_test = x_test.reshape(x_test.shape[0], image_vector)

We will now load the Decision Tree model.

In [0]:
model = DecisionTreeClassifier()

Now we train.

In [5]:
model.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

Now to validate the model created in the last cell.

In [0]:
y_pred = model.predict(x_test)

Now, to display the result.

In [7]:
print("Accuracy:\n", accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", confusion_matrix(y_test, y_pred))
print("Classification Report =\n", classification_report(y_test, y_pred))

Accuracy:
 0.8768
Confusion Matrix =
 [[ 916    0    7    5    4   10   14    8    9    7]
 [   1 1089    9    7    1    3    6    3   14    2]
 [   8   10  888   35   11   12   12   29   20    7]
 [   6    5   30  860    8   44    3    7   26   21]
 [   5    3    4    4  858   14   20   10   21   43]
 [   9   10    4   45    9  749   21    4   26   15]
 [  17    4   12    9   18   23  846    0   25    4]
 [   5   10   31   17    8    4    4  921    7   21]
 [   9    7   26   40   24   34   18   11  780   25]
 [  14    3    5   17   47   10    6   22   24  861]]
Classification Report =
               precision    recall  f1-score   support

           0       0.93      0.93      0.93       980
           1       0.95      0.96      0.96      1135
           2       0.87      0.86      0.87      1032
           3       0.83      0.85      0.84      1010
           4       0.87      0.87      0.87       982
           5       0.83      0.84      0.83       892
           6       0.89    