#Random Forest

In this module, we will see the classification of the MNIST dataset using multiple Decision Trees. 

First we will import the packages needed for classification in sklearn.ensemble. The final accuracy is measured using the sklearn.metrics. Luckily, Keras already provides the MNIST dataset in keras.datasets.mnist.

In [1]:
from keras.datasets import mnist
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Using TensorFlow backend.


Now, we will load the datasets into four variables.

In [0]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

We will reshape the data so that it can be classified by the model.

In [0]:
image_vector = 28 * 28
x_train = x_train.reshape(x_train.shape[0], image_vector)
x_test = x_test.reshape(x_test.shape[0], image_vector)

We will now load the Decision Tree model.

In [0]:
model = RandomForestClassifier(max_depth=10)

Now we train.

In [5]:
model.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

Now to validate the model created in the last cell.

In [0]:
y_pred = model.predict(x_test)

Now, to display the result.

In [7]:
print("Accuracy:\n", accuracy_score(y_test, y_pred))
print("Confusion Matrix =\n", confusion_matrix(y_test, y_pred))
print("Classification Report =\n", classification_report(y_test, y_pred))

Accuracy:
 0.9285
Confusion Matrix =
 [[ 962    1    0    1    0    2    9    1    3    1]
 [   0 1113    6    1    1    2    7    0    5    0]
 [   9    1  952   13    8    3   10   14   17    5]
 [   3    2   21  906    2   32    2   10   22   10]
 [   2    1    3    2  895    2    9    4   13   51]
 [   7    3    4   28    9  802   10    4   12   13]
 [  18    2    7    0    6   10  905    1    9    0]
 [   2   12   32    3    7    0    1  942    6   23]
 [   4    6    8   19   10   14    8    7  878   20]
 [   5    6    4   13   21    5    1    9   15  930]]
Classification Report =
               precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.92      0.92      0.92      1032
           3       0.92      0.90      0.91      1010
           4       0.93      0.91      0.92       982
           5       0.92      0.90      0.91       892
           6       0.94    